name: WisdomPetMedicine

on:
  push:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDIENTIALS }}

      - name: Login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      -  name: Get Current Date in yyyymmdd format
         run: echo "DATE_TIME=$(date +'%Y%m%d')" >> $GITHUB_ENV


      - name: Build and Push Management Container Image 
        run: | 
          docker build ./Wpm.Api.Management.APi -f ./Wpm.Api.Management.APi/Dockerfile -t ${{ secrets.ACR_LOGIN_SERVER }}/wpm-management-api:${{env.DATE_TIME}}.${{ github.run_number }}
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/wpm-management-api:${{env.DATE_TIME}}.${{ github.run_number }}

     

      - name: Build and Push clinic container Image 
        run: | 
            docker build . -f ./Wpm.Clinic/Dockerfile -t ${{ secrets.ACR_LOGIN_SERVER }}/wpm-clinic-api:${{env.DATE_TIME}}.${{ github.run_number }}
            docker push ${{ secrets.ACR_LOGIN_SERVER }}/wpm-clinic-api:${{env.DATE_TIME}}.${{ github.run_number }}

          


      - name: Deploy Management to Azure Container App 
        uses: azure/container-apps-deploy-action@v1
        with:
          resourceGroup: WPM
          containerAppName: wpmcontainerappenv
          imageToDeploy:  ${{ secrets.ACR_LOGIN_SERVER }}/wpm-management-api:${{env.DATE_TIME}}.${{ github.run_number }}
          environmentVariables: Logging__LogLevel__Microsoft.EntityFrameworkCore=Debug
          

      - name: Deploy Clininc to Azure Container App 
        uses: azure/container-apps-deploy-action@v1
        with:
          resourceGroup: WPM
          containerAppName: wpm-clininc
          imageToDeploy:  ${{ secrets.ACR_LOGIN_SERVER }}/wpm-clinic-api:${{env.DATE_TIME}}.${{ github.run_number }}
    
  




      - name: Show Azure Subscription Info
        run: az account show
